version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:admin@postgres:5432/myblog
      REDIS_URL: redis://redis:6379
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: myblog
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"