cache:
  redis:
    addr: redis:6379
    # addr: 127.0.0.1:6379  # Use this line if you are not using docker-compose
    db: 0
  type: redis
credentials:
  key: _
  secret: _
database:
  connect_timeout: 10
  # host: 127.0.0.1  # Use this line if you are not using docker-compose
  host: postgres
  name: myblog
  password: admin
  port: 5432
  sslmode: disable
  user: postgres
server:
  addr: 0.0.0.0
  port: 8080
